### ISSUE TITLE
Correct share links

### ISSUE THREAD

**Issue by flothesof** [remusao/remusao.github.io#202]
Symptom: the share links feature double slashes between the blog domain and their location. 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/2360669/79960045-343ab180-8485-11ea-9028-ba411e524479.png">

I've tracked it down to the template literals found here:
```typescript
<footer>
  <div class="share">
    ${createButtons(post.title, `${blogDomain}${post.url}`)}
  </div>
</footer>
```
If I'm correct, your blog use the convention that all local urls should start with `/`.
Hence, the only correction needed would be to remove the extra slash from the domain, i.e. here.
https://github.com/remusao/remusao.github.io/blob/bc37e5ddcc3b4e0119d8964da21c8756993a082c/index.ts#L24

What do you think?

**Comment by remusao** [comment]
Thanks @flothesof, I have fixed this issue in https://github.com/remusao/remusao.github.io/commit/99c7a2e39596958d70f8ddf7f79bcfeb35e27e7e.

(And sorry it took a year to answer, I totally forgot about this :D)
