### ISSUE TITLE
Comments: What's in a parser combinator?

### ISSUE THREAD

**Issue by Scarysize** [remusao/remusao.github.io#313]
Hey, enjoyed your post about parser combinators: https://remusao.github.io/posts/whats-in-a-parser-combinator.html

I would love to republish a Scala version of this on my personal blog. Would be ok with that? Of course I'll give you due credit and link back to the original post.

**Comment by remusao** [comment]
Hey @Scarysize, I'm really sorry but I somehow missed your message 3 years ago :) I guess it's a bit late and you likely lost interest but for the record, I'm totally fine with you using the content from my blog with attribution. Thanks for asking!

**Comment by Scarysize** [comment]
@remusao Thanks for coming back after such a long time. I had totally forgotten about this. I actually have some free time coming up, I might actually create a Scala version of your post!
