### ISSUE TITLE
Wine seems very complicted now (April 2021)

### ISSUE THREAD

**Issue by DiabloGamer** [remusao/remusao.github.io#505]
Hello  Remusao,

First a BIG thanks for your guide. It's much appreciated. I recently installed Ubuntu 20.04.2 and was thinking of installing a VM and run windows to play Diablo 2 so I did some research and this is when I found your post so I decided to give it a try. I double checked on Wine's website and discovered there were few steps not mentioned in your port. Is it because they're not necessary or because your post is from a while ago and things changed at Wine?
For example, on their webpage: https://wiki.winehq.org/Ubuntu they say that you have to do a sudo update and eventually sudo upgrade. One of their guys even told me "The sudo apt update command doesn't install anything; it merely checks the metadata for all the repositories in your /etc/apt/sources.list--that's how it knows to tell you that there are other packages on your system that have newer versions available. You need to run it (sudo upgrade) whenever you add a new repository, or apt won't know what's in it."

Then, lower on the page it says something about compiling WoW64 and you don't mention that in your post. That paragraph as a link https://wiki.winehq.org/Building_Biarch_Wine_On_Ubuntu and there it seems to say it's essential to do this step. Really^ You don't mention that and it seems to work fine.

I've done the steps you mentionned and alos did the update-upgrasde since according to Wine's staff, it's a necessary step. But do I have to do the WoW64 thing to? WHat's your position on that?

Thanks! :)

**Comment by remusao** [comment]
Hey @DiabloGamer,

Sorry I'm only seeing this message of yours now. Regarding the `apt update`, as far as I know it is not necessary anymore (it used to be), and adding a new ppa will automatically run this command for you.

Regarding the Wow64 I don't think it is needed. I have been able to install Diablo 2 without any issue on my laptop on Ubuntu 20.04 with only the steps mentioned in the post.

Best,
